name: Deploy to branches tied to environments

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'

jobs:
  fume:
    name: Deploy with Fume
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: fumeapp/action@master
        with:
          token: ${{ secrets.FUME_TOKEN }}
          environment: ${GITHUB_REF##*/}
